feat(validate): addition of validation functionality
mbank-design/svgo pull request #1
Opened 2021-07-14 20:31 UTC by tymzar

2021-07-22 09:01 UTC, warsawgentleman commented on lib/svgo.js
> +  if (config == null) {
Sprawdzajmy razem z typem, czyli przez przetrójne `===` :) Dotyczy wszystkich miejsc poniżej :)

2021-07-22 09:01 UTC, warsawgentleman commented on lib/svgo.js
> +  if (Array.isArray(plugins) === false) {
Tutaj wystarczy 
```
if (!Array.isArray(plugins))
```

2021-07-22 09:01 UTC, warsawgentleman commented on lib/svgo.js
> +    // console.log('config.plugins', config.plugins);
To pewnie trzeba by jakoś obsłużyć? A jak nie to do wywalenia :)

2021-07-22 09:01 UTC, warsawgentleman commented on lib/svgo/coa.js
>          var data = '',
`var` alert!

2021-07-22 09:01 UTC, warsawgentleman commented on lib/svgo/coa.js
> +  var startTime = Date.now();
var alert

2021-07-22 09:01 UTC, warsawgentleman commented on lib/svgo/coa.js
> +  var result = null;
Nie możemy od razu zadeklarować `result` jako

```
const result = validate(data, fileName, type, {
    ...config,
    ...info,
  });
```
?

2021-07-22 09:01 UTC, warsawgentleman commented on lib/svgo/coa.js
> +  console.log(result);
Te console.logi potrzebne?

2021-07-22 09:01 UTC, warsawgentleman commented on lib/svgo/config.js
> +const validatePluginsOrder = ['isArtboardCorrect', 'isSnakeCase'];
Nazwę zmiennej, która jest konfiguracyjna możemy pisać UPPER_SNAKE_CASE'em - jest to wskazówka dla czytającego, żeby potem nie próbował modyfikować tej zmiennej :)

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/areFillsNone.js
> +  let result = false;
`result` można by od razu zadeklarować :)

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/areFillsNone.js
> +  let allElements = utils.findAllElementByAttribute(root, 'fill');
To chyba może być constem?

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/areFillsNone.js
> +function checkIfAllFillsAreNone(elements) {
Te funkcję można by opykać przy pomocy `some`/`every` :)

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/areNoDiacriticCharacters.js
> +    filename = filename.substring(0, filename.length - 4);
Ta 4 to jakiś magic number? Jak tak to warto to przypisać do conta, żeby było wiadomo skąd się wzięła :)

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/areNoDiacriticCharacters.js
> +    var result = true;
var alert

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/isArtboardCorrect.js
> +    if (compareArrayCells(viewBox, params.size)) {
`const result = compareArrayCells(viewBox, params.size)` ? :)

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/isArtboardCorrect.js
> +  let result = [];
To można od razu przy deklaracji wygenerować tablicę, poprzez `map` :)

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/isPrefixPresent.js
> +    var result = false;
Tutaj wydaje się, że `result` też można ogarnąć w sposób deklaratywny, czyli 
```
const result = prefixes.some....
```

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/isSVG.js
> +    if (svgTag.name === 'svg' && ext === 'svg') {
```
const result = svgTag.name === 'svg' && ext === 'svg'
```
?

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/isSnakeCase.js
> +    filename = filename.substring(0, filename.length - 4);
Tutaj to jest ok, że zmieniamy `filename`? I jakby co znowu mamy magic number - 4 :)

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/isWorkingAreaCorrect.js
> +    if (
```
const result = checkWorkingArea(workingAreaSize, boundingSize) &&
      ArtboardCordiantes[0] <= workingArea[0] &&
      ArtboardCordiantes[1] <= workingArea[1]
```
? :)

2021-07-22 09:01 UTC, warsawgentleman commented on pluginsValidate/numberOfAllowedPaths.js
> +    let result = false;
Tutaj podobnie jak wyżej :) Można to pyknąć w sposób deklaratywny

2021-07-22 09:01 UTC, warsawgentleman commented on test/pluginsValidate/_index.js
> +      let filePath = PATH.resolve(__dirname, file);
const ;)

2021-07-22 09:01 UTC, warsawgentleman commented on test/pluginsValidate/_index.js
> +    var match = file.match(regFilename),
var alert

2021-07-22 09:01 UTC, warsawgentleman commented on test/pluginsValidate/_index.js
> +          } else if (name === 'areNoDiącritićCharacters') {
Tutaj polskie znaki są legitne? :D

2021-07-22 09:01 UTC, warsawgentleman commented on test/pluginsValidate/_index.js
> +          should = should === 'true';
Tu nie wiem co się dzieje :D

2021-07-22 09:14 UTC, antoni requested changes
Dwie generalne uwagi:
1. Staraj się używać `const` wszędzie gdzie to możliwe
2. Używaj operatora `===` zamiast `==`

2021-07-22 09:14 UTC, antoni commented on lib/svgo.js
> +  if (config == null) {
Lepiej jest wszędzie używać operatora `===`

2021-07-22 09:14 UTC, antoni commented on lib/svgo.js
> +  let svgjs = null;
Tutaj możesz użyć `const`a, jeśli tylko przeniesiesz te inicjalizację kilka linijek niżej (`const svgjs = svg2js(input);`)

2021-07-22 09:14 UTC, antoni commented on pluginsValidate/validatePluginConfig.js
> +        name: 'areNoDiacriticCharacters',
`hasNoDiacriticCharacters`?

2021-07-22 09:14 UTC, antoni commented on test/svgo/_index.js
> +  it('should validate() return an object', async () => {
"validate() should return an object"?

2021-07-22 09:14 UTC, antoni commented on test/svgo/_index.js
> +  it('should validate() do not crash and inform on invalid file type', async () => {
"validate() should not crash and inform on invalid file type"

2021-07-22 09:14 UTC, antoni commented on test/pluginsValidate/areFillsNone_01.svg
> +false
Trochę średnio, że trzymamy w pliku SVG rzeczy, które nie są kodem SVG. Idealnie jakby dało się tego uniknąć, np. trzymając wynik testu w osobnym pliku.

2021-07-22 09:14 UTC, antoni commented on test/coa/_index.js
> +      // await del('temp.svg');
Komentarz do usunięcia lub odkomentowania

2021-07-22 09:14 UTC, antoni commented on test/coa/_index.js
> +    await new Promise((resolve) => setTimeout(resolve, 10));
Ten pause i ten z linijki 147 jest do usunięcia

2021-07-22 09:14 UTC, antoni commented on test/pluginsValidate/_index.js
> +const EOL = require('os').EOL;
Używamy takiej konwecji (upper case) tylkok dla stałych. Tu wystarczy:

```
const fs = require('fs');
const path = require('path');
const EOL = require('os').EOL;
```
(EOL jest stałą)

2021-07-22 09:14 UTC, antoni commented on test/pluginsValidate/_index.js
> +
Niepotrzebna nowa linia

2021-07-22 09:14 UTC, antoni commented on lib/svgo.js
> +    // console.log('config.plugins', config.plugins);
Niepotrzebna linia

2021-07-22 09:14 UTC, antoni commented on lib/svgo.js
> +  let svgjs = null;
Oprócz tego zmieniłbym nazwę na coś w stylu `svgAsJs`. `svgjs` wymaga pełnego zrozumienia kontekstu (równie dobrze w ten posób mogłaby się nazywać funkcja konwertująca SVG na JS)

2021-07-22 09:14 UTC, antoni commented on lib/svgo.js
> +  if (svgjs.error != null) {
`  if (svgjs.error !== null) {`

2021-07-22 09:14 UTC, antoni commented on lib/svgo.js
> +    if (config.path != null) {
`    if (config.path !== null) {`

2021-07-22 09:14 UTC, antoni commented on lib/svgo.js
> +  if (Array.isArray(plugins) === false) {
`if (!Array.isArray(plugins)) {`

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +    .option('--asset-type <TYPE...>', 'Input asset type')
Dobrze byłoby tu dopsiać jakie wartości dopuszczamy w tym miejscu

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +      if (opts.validate != null && opts.assetType && input.length == 1) {
`==` → `===`

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +          input.map((file, n) =>
Generalna zasada: nie używamy skrótów :)
(nawet w przypadku zmiennych typu `i`, `j`)

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +        console.error('error: provide exactly one svg file to validate');
"svg" → "SVG"

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +          input.map((file, n) => optimizeFile(config, file, output[n]))
Rozwiń nazwę zmiennej `n`

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +function validateSVGData(config, info, data, output, input, fileName, type) {
`validateSVGData` → `validateSvgData`

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +  var startTime = Date.now();
`var` → `const`

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +  var result = null;
`var` → `const`

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +  console.log(result);
Lepiej to napisać jednym console.logiem

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +  var processingTime = Date.now() - startTime;
`var` → `const`

2021-07-22 09:14 UTC, antoni commented on lib/svgo/coa.js
> +      processSVGData(config, { input: 'file', path: file }, data, output, file);
`processSVGData` → `processSvgData`

2021-07-22 09:14 UTC, antoni commented on lib/svgo/config.js
> +const validatePluginsOrder = ['isArtboardCorrect', 'isSnakeCase'];
Idealnie byłoby jakby te nazwy reguł walidacji pochodziłī z jakichś stałych

2021-07-23 19:37 UTC, tymzar commented on lib/svgo/coa.js
> +  console.log(result);
Yep, nie ma loggera, a inaczej przy użyciu cli nie byłoby pojęcia, jaki jest wynik ;>

2021-07-23 19:40 UTC, tymzar commented on pluginsValidate/areNoDiacriticCharacters.js
> +    filename = filename.substring(0, filename.length - 4);
Zmieniłem podejście bo zamysł był średni i dodałem comm'a
PS w wolnym czasie lubię czarować i to był powód :D

2021-07-23 19:45 UTC, tymzar commented on pluginsValidate/isWorkingAreaCorrect.js
> +    if (
Dodałem nazwy "bardziej" opisowe, jednak obliczenia koordynatów chyba nigdy nie wyglądają dobrze c:

2021-07-23 19:48 UTC, tymzar commented on test/pluginsValidate/_index.js
> +          } else if (name === 'areNoDiącritićCharacters') {
Si, niestety automatyzacja testów stworzona przez svgo nie przewidywała naszych plugin'ów ;>

2021-07-23 19:49 UTC, tymzar commented on test/pluginsValidate/_index.js
> +          should = should === 'true';
Same, ale wątpię, że pytanie się przez issues twórcy systemu testów svgo pomoże xd

2021-07-23 19:53 UTC, tymzar commented on lib/svgo.js
> +  let svgjs = null;
Podmieniłem, racja mogło to być mylące (btw zapożyczyłem ją od twórców :> )

2021-07-23 19:59 UTC, tymzar commented on test/svgo/_index.js
> +  it('should validate() return an object', async () => {
zmieniłem na "should validate svg and return an object with property {isSVG: true}"

2021-07-23 19:59 UTC, tymzar commented on test/svgo/_index.js
> +  it('should validate() do not crash and inform on invalid file type', async () => {
oraz "should try to validate pdf and return an object with property {isSVG: false}"

2021-07-23 20:01 UTC, tymzar commented on test/coa/_index.js
> +    await new Promise((resolve) => setTimeout(resolve, 10));
Właśnie z nie wiem czemu, ale po ich usunięciu oba testy nie przechodzą :?

2021-07-23 20:02 UTC, tymzar commented on test/pluginsValidate/_index.js
> +const EOL = require('os').EOL;
Zapamiętam, kopiowałem to z ich testów :D

2021-07-23 20:05 UTC, tymzar commented on lib/svgo/coa.js
> +          input.map((file, n) =>
Jasne, nawyk z cpp się kłania, ale koledzy z svgo chyba mają podobnie :>

2021-07-23 20:09 UTC, tymzar commented on lib/svgo/config.js
> +const validatePluginsOrder = ['isArtboardCorrect', 'isSnakeCase'];
Ta funkcjonalność poszła w niebyt, uznałem że definiowanie default'owej listy plugin'ów walidacyjnych trochę mija się z celem

2021-07-27 10:47 UTC, warsawgentleman commented on lib/svgo/coa.js
> +      if (opts.validate != null && opts.assetType && input.length === 1) {
Tutaj `!=` powiniśmy zamienić na `!==` :)

2021-07-27 10:47 UTC, warsawgentleman commented on lib/svgo/coa.js
> +  if (!config.quiet && output != '-') {
`!=` => `!==`

2021-07-27 10:47 UTC, warsawgentleman commented on pluginsValidate/isArtboardCorrect.js
> +    root.children[0].attributes.viewBox != null
`!=` => `!==`

2021-07-27 10:47 UTC, warsawgentleman commented on pluginsValidate/isWorkingAreaCorrect.js
> +    root.children[0].attributes.viewBox != null
`!=` => `!==`

2021-07-27 12:38 UTC, warsawgentleman approved these changes

2021-07-28 13:28 UTC, merged