feat: add hasColorSuffix rule
mbank-design/svgo pull request #10
Opened 2023-03-10 13:18 UTC by Arwer234

2023-03-10 13:28 UTC, tymzar requested changes
Z tego co pamętam ten rule powinien być dla oby typów ikon c;

2023-03-10 13:40 UTC, tymzar commented on pluginsValidate/hasColorSuffix.js
> +      result = true;
Powinno być odwrotnie c;

2023-03-10 16:26 UTC, Arwer234 commented on pluginsValidate/hasColorSuffix.js
> +      result = true;
Zrobione :)

2023-03-13 08:19 UTC, tymzar approved these changes

2023-03-13 08:42 UTC, merged